language: csharp
mono: none
dotnet: 2.1.502
solution: Cactus.Blade.Configuration.ProxyFactory.sln
install:
  - dotnet restore
script:
  - dotnet msbuild /p:Configuration.ProxyFactory=Release Cactus.Blade.Configuration.ProxyFactory.sln
  - dotnet restore
  - dotnet test Configuration.ProxyFactory.Test/Configuration.ProxyFactory.Test.csproj
